### ISSUE TITLE
有没有用到实际生产环境中的，感觉window下nginx和php容易奔

### ISSUE THREAD

**Issue by shilcheng** [baofan/SalamanderWnmp#21]
有没有用到实际生产环境中的，感觉window下nginx和php容易奔，如果再把apache弄进来就好了，apache+php nginx负责代理，转发就完美了 肯定没问题

**Comment by salamander-mh** [comment]
这只是测试学习用的环境，windows下nignx都不能用epoll，php也只是跑php-cgi这个进程（而不是php-fpm）。
另外，现在也有docker和wsl了，开发环境也很好配置了
